info:
  title: Admin Airbean API
  description: API documentation for Admin Airbean API
  version: 1.0.0
openapi: 3.1.0
components: 
paths:
  api/logout:
    get:
  api/login:
    post:
  api/register:
    post:
  api/menu:
    post:
  api/menu/{prodId}:
    put:
  api/menu/{prodId}:
    delete: